version: '3.8'

networks:
  prod-network:
    name: prod-network

services:
  traefik:
    image: "traefik:v2.10"
    container_name: bw-traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=dev-network"
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - prod-network
    labels:
      - "traefik.enable=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=dev-network"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: bw-rabbitmq
    hostname: rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt &&
         rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - prod-network
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.rabbitmq-dashboard.rule=Host(`${RABBIT_DASHBOARD_SUBDOMAIN}.${DOMAIN}`) && !PathPrefix(`/ws`)" # Path-based routing
      - "traefik.http.routers.rabbitmq-dashboard.entrypoints=web"
      - "traefik.http.routers.rabbitmq-dashboard.service=rabbitmq-dashboard"
      - "traefik.http.services.rabbitmq-dashboard.loadbalancer.server.port=15672"
      # MQTT
      - "traefik.http.routers.rabbitws.rule=Host(`${RABBIT_WS_SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.rabbitws.entrypoints=web"
      - "traefik.http.routers.rabbitws.service=rabbitws"
      - "traefik.http.services.rabbitws.loadbalancer.server.port=15675"
      - "traefik.http.services.rabbitws.loadbalancer.server.scheme=http"

  web:
    image: campinavrienden/bingoweb:latest
    container_name: bw-web
    env_file:
      - .env
    networks:
      - prod-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.vite.rule=Host(`${WEB_SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.vite.entrypoints=web
      - traefik.http.services.vite.loadbalancer.server.port=80